### ISSUE TITLE
ISBN in Finna API

### ISSUE THREAD

**Issue by nemobis** [NatLibFi/Finna-client#2]
Hi Osma, thank you for the documentation and the client.

I've read https://api.finna.fi/swagger-ui/ and https://www.kiwi.fi/pages/viewpage.action?pageId=53839221 and I understand that not all fields are always available.

I wonder though if I'm doing something stupid, because I never manage to see any ISBN code in the data returned from the API. For instance from a [very silly search](https://finna.fi/Search/Results?limit=0&filter%5B%5D=%7Ebuilding%3A%220%2FNLF%2F%22&filter%5B%5D=%7Eformat_ext_str_mv%3A%221%2FBook%2FBook%2F%22&filter%5B%5D=%7Elanguage%3A%22fin%22&filter%5B%5D=%7Eera_facet%3A%222010-luku%22&lookfor=978&type=AllFields) I find [a book with ISBN](https://finna.fi/Record/fikka.4198888) and [its API record](https://api.finna.fi/v1/record?id=fikka.4198888) has no ISBN. If I [search by ISBN](https://api.finna.fi/v1/search?lookfor=978-952-68009-2-9) I do find the record, so the index knows about it, but the API doesn't seem to represent it.

Should I just [ask for the full record](https://api.finna.fi/v1/record?id=fikka.4198888&field[]=fullRecord) and then parse the MARC myself? That's fine too (thank you for making it so easy to access!), just want to be sure.

**Comment by osma** [comment]
Hi @nemobis! I think the problem is that the `record` API call uses a default list of fields to return if you don't specify one. ISBN is not among those fields. Try one of these instead:
https://api.finna.fi/v1/record?id=fikka.4198888&field[]=cleanIsbn
https://api.finna.fi/v1/record?id=fikka.4198888&field[]=isbns

This loses all the other (default) fields though - add the ones you need by passing additional `field[]` values. According to the Swagger spec, the default fields are:

```
    buildings
    formats
    id
    imageRights
    images
    languages
    nonPresenterAuthors
    onlineUrls
    presenters
    rating
    series
    subjects
    title
    urls
```

You should be able to do the same with the Python wrapper by using the `fields` parameter of `get_record` or `get_records`.

**Comment by nemobis** [comment]
Osma Suominen, 03/03/20 13:40:
> Hi @nemobis <https://github.com/nemobis>! I think the problem is that 
> the |record| API call uses a default list of fields to return if you 
> don't specify one. ISBN is not among those fields.

Ah thank you! I knew it must be something silly on my end. Thank you ver 
much.
